---
title: "scIGD on Merkel Cell Carcinoma"
author: "Ahmad Al Ajami"
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: false
    toc: true
    toc_float: true
    toc_depth: 5
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=TRUE, message=FALSE, cache = FALSE}
suppressPackageStartupMessages({
library(SingleCellAlleleExperiment)
library(tidyverse)
library(gridExtra)
library(DropletUtils)
library(BiocParallel)
library(Matrix)
library(AnnotationHub)
library(cowplot)
library(pheatmap)
library(reshape2)
library(scales)
})
```

# SingleCellAlleleExperiment

```{r scae, message=FALSE}
read_scae <- function(folder_path){
  folder_name <- gsub("../data/", "", folder_path)
  counts <- read_allele_counts(folder_path,
                               lookup_file = read.csv(file.path(folder_path, "lookup_table_HLA.csv")),
                               sample_names = folder_name,
                               filter_mode = "yes",
                               log = TRUE,
                               gene_symbols = TRUE)
  return(counts)
}

scae_list <- lapply(c("pbmc_preRx_extra"), function(donor){
  read_scae(file.path("../data", donor)) 
})
```

# Visualization

scIGD -- allele level:

```{r}
scae_com <- scae_list[[1]]

hla_a <- c("A*03:01:01:01", "A*30:01:01:01", "A*02:01:01:01", "A*24:02:01:01")
hla_b <- c("B*13:02:01:01", "B*35:02:01:01", "B*15:01:01:01", "B*44:03:01:01")
hla_c <- c("C*04:01:01:01", "C*06:02:01:01", "C*03:03:01:01", "C*16:01:01:01")

allele_data <- data.frame(
    Gene = rep(c("HLA-A", "HLA-B", "HLA-C"), each = 4),
    Allele = c(hla_a, hla_b, hla_c)
)

p <- lapply(unique(allele_data$Gene), function(gene) {
    plotExpression(scae_com, allele_data$Allele[allele_data$Gene == gene]) +
        ggtitle(gene) +
        theme_bw() +
        theme(axis.text.x = element_text(angle = 45, hjust = 1, size=14),
              axis.text.y = element_text(size = 14),
              axis.title.y=element_blank(),
              plot.title = element_text(size = 14)) +
        scale_color_manual(values = c("black","black", "steelblue", "steelblue")) +
        scale_fill_manual(values = c("black","black", "steelblue", "steelblue"))
})

combined_plot <- gridExtra::grid.arrange(grobs = p, ncol = 3)

y_label <- ggdraw() +
    draw_label("expression (logcounts)", 
               angle = 90, 
               size = 14, 
               vjust = 0.2,
               x=0.5,
               y=0.6)

fig3c <- plot_grid(y_label, combined_plot, ncol = 2, rel_widths = c(0.05, 1))
ggsave("Fig3c.pdf", fig3c, height = 6, width = 18)
save(fig3c, file = "fig3c.RData")
```

```{r}
alleles <- c(hla_a, hla_b, hla_c)

num_alleles <- length(alleles)
similarity_matrix <- matrix(NA, nrow = num_alleles, ncol = num_alleles)

# Fill in the similarity scores for A alleles
similarity_matrix[1, 2] <- 99.1
similarity_matrix[1, 3] <- 96.1
similarity_matrix[1, 4] <- 97.3
similarity_matrix[2, 3] <- 95.9
similarity_matrix[2, 4] <- 97.2
similarity_matrix[3, 4] <- 96.0

# Fill in the similarity scores for B alleles
similarity_matrix[5, 6] <- 88.0
similarity_matrix[5, 7] <- 95.5
similarity_matrix[5, 8] <- 95.5
similarity_matrix[6, 7] <- 86.1
similarity_matrix[6, 8] <- 85.5
similarity_matrix[7, 8] <- 97.9

# Fill in the similarity scores for C alleles
similarity_matrix[9, 10] <- 93.2
similarity_matrix[9, 11] <- 93.1
similarity_matrix[9, 12] <- 93.0
similarity_matrix[10, 11] <- 98.2
similarity_matrix[10, 12] <- 99.2
similarity_matrix[11, 12] <- 98.2

# Fill in cross-allele scores
similarity_matrix[1, 5] <- 71.8
similarity_matrix[1, 6] <- 79.9
similarity_matrix[1, 7] <- 70.3
similarity_matrix[1, 8] <- 70.3
similarity_matrix[1, 9] <- 70.6
similarity_matrix[1, 10] <- 66.9
similarity_matrix[1, 11] <- 66.9
similarity_matrix[1, 12] <- 66.9

similarity_matrix[2, 5] <- 72.0
similarity_matrix[2, 6] <- 80.1
similarity_matrix[2, 7] <- 70.5
similarity_matrix[2, 8] <- 70.5
similarity_matrix[2, 9] <- 70.8
similarity_matrix[2, 10] <- 67.1
similarity_matrix[2, 11] <- 67.1
similarity_matrix[2, 12] <- 67.1

similarity_matrix[3, 5] <- 72.0
similarity_matrix[3, 6] <- 80.1
similarity_matrix[3, 7] <- 70.5
similarity_matrix[3, 8] <- 70.6
similarity_matrix[3, 9] <- 70.9
similarity_matrix[3, 10] <- 67.0
similarity_matrix[3, 11] <- 67.1
similarity_matrix[3, 12] <- 67.1

similarity_matrix[4, 5] <- 72.4
similarity_matrix[4, 6] <- 80.3
similarity_matrix[4, 7] <- 70.6
similarity_matrix[4, 8] <- 70.8
similarity_matrix[4, 9] <- 70.8
similarity_matrix[4, 10] <- 66.9
similarity_matrix[4, 11] <- 67.0
similarity_matrix[4, 12] <- 67.1
  
similarity_matrix[5, 9] <- 82.3
similarity_matrix[5, 10] <- 84.1
similarity_matrix[5, 11] <- 83.7
similarity_matrix[5, 12] <- 84.0

similarity_matrix[6, 9] <- 79.8
similarity_matrix[6, 10] <- 75.8
similarity_matrix[6, 11] <- 75.8
similarity_matrix[6, 12] <- 75.9

similarity_matrix[7, 9] <- 80.5
similarity_matrix[7, 10] <- 85.6
similarity_matrix[7, 11] <- 85.1
similarity_matrix[7, 12] <- 85.5
  
similarity_matrix[8, 9] <- 80.5
similarity_matrix[8, 10] <- 85.5
similarity_matrix[8, 11] <- 85.2
similarity_matrix[8, 12] <- 85.4

diag(similarity_matrix) <- 100.0

rownames(similarity_matrix) <- alleles
colnames(similarity_matrix) <- alleles

data_long <- melt(similarity_matrix, na.rm = TRUE)

custom_palette <- c("blue", "lightblue", "yellow", "orange", "red")
fig3d <- ggplot(data_long, aes(x = Var2, y = factor(Var1, levels = rev(levels(Var1))), fill = value)) +
    geom_tile(color = "black") +  
    scale_fill_gradientn(colors = custom_palette, 
                         values = rescale(c(0, 80, 85, 90, 95, 100))) +  
    theme_minimal() +
    scale_x_discrete(position = "top") +
    theme(axis.text.x = element_text(angle = 45, hjust = 0, vjust = 1, size = 14),
          axis.text.y = element_text(size = 14),
          legend.title = element_text(size = 14),
          legend.text = element_text(size = 14)) +  
    labs(x = "", y = "", fill = "Similarity Score (%)") +
    coord_fixed()

ggsave("Fig3d.pdf", fig3d, height = 6, width = 8)
save(fig3d, file = "fig3d.RData")
```

# Session

```{r sessionInfo, cache = 0}
sessionInfo()
```

