---
title: "scIGD on AIDA"
author: "Ahmad Al Ajami"
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: false
    toc: true
    toc_float: true
    toc_depth: 5
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=TRUE, message=FALSE, cache = FALSE}
suppressPackageStartupMessages({
library(SingleCellExperiment)
library(tidyverse)
library(gridExtra)
library(cowplot)
library(immunotation)
})
```

```{r}
filtered_scae_list <- readRDS("scae.Rds")
```

# Korean

8 samples

```{r}
kr_scae <- filtered_scae_list[sapply(filtered_scae_list, function(.) {
  any(.$Nationality == "KR")
})]
```

```{r}
df <- lapply(kr_scae, function(sce){
    data.frame(allele = rownames(sce[rowData(sce)$Quant_type == "A", ])) %>%
        mutate(gene = paste0("HLA-", str_extract(allele, "^[^*]+")))}) %>% 
    bind_rows() %>% 
    arrange(gene) %>% 
    group_by(allele, gene) %>%
    mutate(count = n()) %>% 
    distinct(allele, gene, .keep_all = TRUE) %>%
    #filter(gene %in% c("HLA-A", "HLA-B", "HLA-C"))
    filter(gene %in% c("HLA-A"))

p1 <- by(data = df, INDICES = df$gene, FUN = function(m) {
    m <- droplevels(m)
    m <- ggplot(m, aes(x = allele, y = count)) +
        geom_bar(stat = "identity", width = 0.5) +
        theme_bw() +
        theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
        facet_wrap(~gene) +
        ggtitle("KR (n=8)") +
        labs(y = "frequency of typed alleles") +
        theme(plot.title = element_text(size = 14),
              strip.text = element_text(size = 14),
              axis.title.x=element_blank(),
              axis.title.y=element_text(size = 14, margin = margin(r = 15)),
              axis.text.x = element_text(size = 14),
              axis.text.y = element_text(size = 14))
})

#do.call(grid.arrange, c(p, ncol=1))
```

```{r}
df <- lapply(kr_scae, function(sce){
    data.frame(allele = rownames(sce[rowData(sce)$Quant_type == "A", ])) %>%
        mutate(gene = paste0("HLA-", str_extract(allele, "^[^*]+")))}) %>% 
    bind_rows() %>% 
    arrange(gene) %>% 
    group_by(allele, gene) %>%
    mutate(count = n()) %>% 
    distinct(allele, gene, .keep_all = TRUE) %>%
    #filter(gene %in% c("HLA-A", "HLA-B", "HLA-C"))
    filter(gene %in% c("HLA-C"))

p2 <- by(data = df, INDICES = df$gene, FUN = function(m) {
    m <- droplevels(m)
    m <- ggplot(m, aes(x = allele, y = count)) +
      geom_bar(stat = "identity", width = 0.5) +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
      facet_wrap(~gene) +
      ggtitle("KR (n=8)") +
      labs(y = "frequency of typed alleles") +
        theme(plot.title = element_text(size = 14),
              strip.text = element_text(size = 14),
              axis.title.x=element_blank(),
              axis.title.y=element_text(size = 14, margin = margin(r = 15)),
              axis.text.x = element_text(size = 14),
              axis.text.y = element_text(size = 14))
})
```

# Japanese

6 samples

```{r}
jp_scae <- filtered_scae_list[sapply(filtered_scae_list, function(.) {
  any(.$Nationality == "JP")
})]
```

```{r}
df <- lapply(jp_scae, function(sce){
    data.frame(allele = rownames(sce[rowData(sce)$Quant_type == "A", ])) %>%
        mutate(gene = paste0("HLA-", str_extract(allele, "^[^*]+")))}) %>% 
    bind_rows() %>% 
    arrange(gene) %>% 
    group_by(allele, gene) %>%
    mutate(count = n()) %>% 
    distinct(allele, gene, .keep_all = TRUE) %>%
    #filter(gene %in% c("HLA-A", "HLA-B", "HLA-C"))
    filter(gene %in% c("HLA-A"))

p3 <- by(data = df, INDICES = df$gene, FUN = function(m) {
    m <- droplevels(m)
    m <- ggplot(m, aes(x = allele, y = count)) +
        geom_bar(stat = "identity", width = 0.5) +
        theme_bw() +
        theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
        facet_wrap(~gene) +
        ggtitle("JP (n=6)") +
        theme(plot.title = element_text(size = 14),
              strip.text = element_text(size = 14),
              axis.title.x=element_blank(),
              axis.title.y=element_blank(),
              axis.text.x = element_text(size = 14),
              axis.text.y = element_text(size = 14))
})
```

```{r}
df <- lapply(jp_scae, function(sce){
    data.frame(allele = rownames(sce[rowData(sce)$Quant_type == "A", ])) %>%
        mutate(gene = paste0("HLA-", str_extract(allele, "^[^*]+")))}) %>% 
    bind_rows() %>% 
    arrange(gene) %>% 
    group_by(allele, gene) %>%
    mutate(count = n()) %>% 
    distinct(allele, gene, .keep_all = TRUE) %>%
    #filter(gene %in% c("HLA-A", "HLA-B", "HLA-C"))
    filter(gene %in% c("HLA-C"))

p4 <- by(data = df, INDICES = df$gene, FUN = function(m) {
    m <- droplevels(m)
    m <- ggplot(m, aes(x = allele, y = count)) +
        geom_bar(stat = "identity", width = 0.5) +
        theme_bw() +
        theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
        facet_wrap(~gene) +
        ggtitle("JP (n=6)") +
        theme(plot.title = element_text(size = 14),
              strip.text = element_text(size = 14),
              axis.title.x=element_blank(),
              axis.title.y=element_blank(),
              axis.text.x = element_text(size = 14),
              axis.text.y = element_text(size = 14))
})
```

```{r}
fig3a <- plot_grid(p1$`HLA-A`, p3$`HLA-A`, align = "hv", nrow=1, rel_widths = c(1.4, 1))
ggsave("Fig3a.pdf", fig3a, height = 6, width = 7)
ggsave("Fig3a.tiff", fig3a, height = 6, width = 7)
save(fig3a, file = "fig3a.RData")

suppfig1a <- plot_grid(p2$`HLA-C`, p4$`HLA-C`, align = "hv", nrow=1, rel_widths = c(1.2, 1.2))
ggsave("Suppfig1a.pdf", suppfig1a, height = 6, width = 8)
ggsave("Suppfig1a.tiff", suppfig1a, height = 6, width = 7)
save(suppfig1a, file = "suppfig1a.RData")
```

# Immunotation -- Allele Frequency

First example

```{r}
sel1 <- query_allele_frequencies(hla_selection = "A*24:02", 
                                 hla_sample_size_pattern = "bigger_than", 
                                 hla_sample_size = 1000, 
                                 standard = "g")

DT::datatable(sel1)
```

```{r}
top_5_populations <- sel1 %>%
    arrange(desc(allele_frequency)) %>%
    head(7)

p1 <- ggplot(top_5_populations, aes(x = reorder(population, -allele_frequency), y = allele_frequency)) +
    geom_bar(stat = "identity", fill = "steelblue", width = 0.5) +
    labs(y = "allele_frequency") +
    theme_bw() +
    coord_flip() + 
    theme(plot.title = element_text(size = 14),
          axis.title.x=element_text(size = 14),
          axis.title.y=element_blank(),
          axis.text.x = element_text(size = 14),
          axis.text.y = element_text(size = 14)) 

p2 <- plot_allele_frequency(sel1) + 
      theme(axis.text.x = element_text(size = 14),
            axis.text.y = element_text(size = 14),
            legend.title = element_text(size = 14),
            legend.text = element_text(size = 14))
save(p2, file = "fig1bp2.RData")
load("fig1bp2.RData")
```

```{r}
p <- plot_grid(p1, p2, nrow = 1, align = "h", rel_widths = c(1, 1))
fig3b <- p +
  ggtitle("top populations by allele frequency (HLA-A*24:02)") + 
  theme(plot.title = element_text(hjust = 0.5, vjust=0.8, size = 14))
ggsave("Fig3b.pdf", fig3b, height = 6, width = 12)
ggsave("Fig3b.tiff", fig3b, height = 6, width = 10)
save(fig3b, file = "fig3b.RData")
```

Second example

```{r}
sel1 <- query_allele_frequencies(hla_selection = "C*01:02", 
                                 hla_sample_size_pattern = "bigger_than", 
                                 hla_sample_size = 1000, 
                                 standard = "g")

DT::datatable(sel1)
```

```{r}
top_5_populations <- sel1 %>%
    arrange(desc(allele_frequency)) %>%
    head(8)

p1 <- ggplot(top_5_populations, aes(x = reorder(population, -allele_frequency), y = allele_frequency)) +
    geom_bar(stat = "identity", fill = "steelblue", width = 0.5) +
    labs(y = "allele_frequency") +
    theme_bw() +
    coord_flip() + 
    theme(plot.title = element_text(size = 14),
          axis.title.x=element_text(size = 14),
          axis.title.y=element_blank(),
          axis.text.x = element_text(size = 14),
          axis.text.y = element_text(size = 14)) 

p2 <- plot_allele_frequency(sel1) + 
      theme(axis.text.x = element_text(size = 14),
            axis.text.y = element_text(size = 14),
            legend.title = element_text(size = 14),
            legend.text = element_text(size = 14))
save(p2, file = "suppfig1bp2.RData")
load("suppfig1bp2.RData")
```

```{r}
p <- plot_grid(p1, p2, nrow = 1, align = "h", rel_widths = c(1, 1))
suppfig1b <- p +
  ggtitle("top populations by allele frequency (HLA-C*01:02)") + 
  theme(plot.title = element_text(hjust = 0.5, vjust=0.8, size = 14))
ggsave("Suppfig1b.pdf", suppfig1b, height = 6, width = 12)
ggsave("Suppfig1b.tiff", suppfig1b, height = 6, width = 10)
save(suppfig1b, file = "suppfig1b.RData")
```

# Session info

```{r sessionInfo, cache = 0}
sessionInfo()
```

