---
title: "scIGD on 20k PBMC"
author: "Ahmad Al Ajami"
date: "`r Sys.Date()`"
output:
  html_document:
    keep_md: false
    toc: true
    toc_float: true
    toc_depth: 5
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=TRUE, message=FALSE, cache = FALSE}
suppressPackageStartupMessages({
library(SingleCellAlleleExperiment)
library(tidyverse)
library(gridExtra)
library(DropletUtils)
library(BiocParallel)
library(scDblFinder)
library(Matrix)
library(AnnotationHub)
library(cowplot)
library(scran)
library(scater)
library(pheatmap)
})
```

# SingleCellAlleleExperiment

```{r scae, message=FALSE}
scae <- readRDS("../intermediate_files/scae.Rds")
```

# SingleCellExperiment

```{r}
read_sce <- function(data){
  cells_dir <- paste0(data, "/cells_x_genes.barcodes.txt")
  cells <- utils::read.csv(cells_dir, sep = "", header = FALSE) 
  
  features_dir <- paste0(data, "/cells_x_genes.genes.txt")
  features <- utils::read.delim(features_dir, header = FALSE)
  
  mat <- Matrix::readMM(paste0(data, "/cells_x_genes.mtx"))
  rownames(mat) <- cells$V1
  colnames(mat) <- features$V1
  
  sce <- SingleCellExperiment(assays = list(counts = t(mat)))

  rownames(sce) <- gsub("\\..*", "", rownames(sce))
  gene_symbols <- ensembldb::select(EnsDb.Hsapiens.v86::EnsDb.Hsapiens.v86, keys= rownames(sce), keytype = "GENEID", columns = c("SYMBOL","GENEID"))
  rowData(sce)$gene_symbol <- gene_symbols$SYMBOL[match(rownames(sce), gene_symbols$GENEID)]
  
  sce$sample <- data

  return(sce)
}

sce <- read_sce("../data/kallisto")
```

# Intersect columns

```{r}
colnames1 <- colnames(scae)
colnames2 <- colnames(sce)
common_colnames <- Reduce(intersect, list(colnames1, colnames2))
scae <- scae[, common_colnames]
sce <- sce[, common_colnames]
```

# Plots

```{r}
top_5_indices <- order(rowSums(counts(scae)), decreasing = TRUE)[1:5]
rownames(counts(scae))[top_5_indices]
```

## Most highly expressed gene

```{r}
plot(counts(scae["ENSG00000251562", ]), counts(sce["ENSG00000251562", ]), xlab="scigd", ylab="kallisto")

plot(counts(scae["ENSG00000210082", ]), counts(sce["ENSG00000210082", ]), xlab="scigd", ylab="kallisto")

plot(counts(scae["ENSG00000198804", ]), counts(sce["ENSG00000198804", ]), xlab="scigd", ylab="kallisto")
```

```{r}
hla_a <- rownames(sce)[which(rowData(sce)$gene_symbol == "HLA-A")]
hla_b <- rownames(sce)[which(rowData(sce)$gene_symbol == "HLA-B")]
hla_c <- rownames(sce)[which(rowData(sce)$gene_symbol == "HLA-C")]
hla_dra <- rownames(sce)[which(rowData(sce)$gene_symbol == "HLA-DRA")]
```

# Studying the correlation 

If the Pearson or Spearman correlation coefficient is close to +1, it indicates a strong positive correlation

A value close to 0 suggests no correlation

A negative value indicates a negative correlation

```{r}
counts_a_1 <- as.numeric(counts(scae["HLA-A", ]))
counts_a_2 <- as.numeric(counts(sce[hla_a, ]))

# calculating correlation coefficient using Pearson or Spearman
correlation_pearson <- cor(counts_a_1, counts_a_2, method = "pearson") %>% round(., digits = 2)
correlation_spearman <- cor(counts_a_1, counts_a_2, method = "spearman") %>% round(., digits = 2)
correlation <- paste("Pearson:", correlation_pearson,
                     "\nSpearman:", correlation_spearman)

data <- data.frame(counts_a_1 = counts_a_1, counts_a_2 = counts_a_2)

p1 <- ggplot(data, aes(x = counts_a_1, y = counts_a_2)) +
    geom_point(color = "blue") +
    geom_smooth(method = "lm", color = "red", se = FALSE) +
    labs(subtitle = "HLA-A",
         y = "expression in kallisto") +
    theme_bw() + 
    theme(plot.subtitle = element_text(size = 14),
          axis.title.x=element_blank(),
          axis.title.y=element_text(size = 14),
          axis.text.x = element_text(size = 14),
          axis.text.y = element_text(size = 14))

p1 <- p1 + annotate("text", x = 25, y = 20,
                  label = correlation, 
                  hjust = 0, vjust = -0.2, 
                  size = 4, 
                  color = "red")
```

```{r}
counts_dra_1 <- as.numeric(counts(scae["HLA-DRA", ]))
counts_dra_2 <- as.numeric(counts(sce[hla_dra, ]))

# calculating correlation coefficient using Pearson or Spearman
correlation_pearson <- cor(counts_dra_1, counts_dra_2, method = "pearson") %>% round(., digits = 2)
correlation_spearman <- cor(counts_dra_1, counts_dra_2, method = "spearman") %>% round(., digits = 2)
correlation <- paste("Pearson:", correlation_pearson,
                     "\nSpearman:", correlation_spearman)

data <- data.frame(counts_dra_1 = counts_dra_1, counts_dra_2 = counts_dra_2)

p2 <- ggplot(data, aes(x = counts_dra_1, y = counts_dra_2)) +
    geom_point(color = "blue") +
    geom_smooth(method = "lm", color = "red", se = FALSE) +
    labs(subtitle = "HLA-DRA") +
    theme_bw() + 
    theme(plot.subtitle = element_text(size = 14),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          axis.text.x = element_text(size = 14),
          axis.text.y = element_text(size = 14))

p2 <- p2 + annotate("text", x =  175, y = 100,
              label = correlation, 
              hjust = 0, vjust = -0.2, 
              size = 4, 
              color = "red")
```

```{r}
combined_plot <- plot_grid(p1, p2, align = "hv", nrow=1)

x_label <- ggdraw() +
  draw_label("expression in scIGD",
             size = 14, 
             vjust = 0.5,
             hjust = 0.35)

p <- plot_grid(combined_plot, x_label, ncol = 1, rel_heights = c(1, 0.05))

fig3d <- p +
  ggtitle("gene expression correlation") + 
  theme(plot.title = element_text(hjust = 0.53, vjust=0.8, size = 14))

ggsave("Fig3d.pdf", fig3d, height = 6, width = 12)
save(fig3d, file = "fig3d.RData")
```

# Session

```{r sessionInfo, cache = 0}
sessionInfo()
```
